package ru.gb.testing.exception

class UserAuthException(msg: String): RuntimeException(msg) {
}